FROM php:8.1-apache

RUN apt-get update
RUN apt-get install -y unzip curl git
RUN curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.2.12

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql

RUN mkdir /usr/local/bin/run
RUN chmod +x /usr/local/bin/run
RUN a2enmod rewrite

#RUN pecl install xdebug \
    # && docker-php-ext-enable xdebug

WORKDIR /var/www
# RUN echo 'xdebug.remote_enable = ${XDEBUG_ENABLED}' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    # echo "xdebug.remote_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini