FROM php:8.1-apache

RUN apt-get update
RUN apt-get install -y unzip curl git
RUN curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.2.12

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql

RUN mkdir /usr/local/bin/run
RUN chmod +x /usr/local/bin/run
RUN a2enmod rewrite

RUN apt-get update -y && apt-get install -y sendmail libpng-dev

RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev 

# RUN docker-php-ext-install mbstring

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

RUN install-php-extensions zip
WORKDIR /var/www
RUN apt install php-zip
RUN apt-get update docker-php-ext-install zip
RUN apt-get update      && apt-get install -y libzip-dev      && docker-php-ext-install zip

RUN apt-get update \
     && apt-get install -y libzip-dev \
     && docker-php-ext-install zip